version: "3.4"

networks:
  krabs-dev:
    driver: bridge
    
services:
  db:
    image: "postgres:11"
    container_name: "krabs-postgres"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - krabs_dbdata:/var/lib/postgresql/data
    networks:
      - krabs-dev
volumes:
  krabs_dbdata: